channels:
  - conda-forge
dependencies:
  - python=3.11
  - scanpy=1.11.4
  - umap-learn=0.5.9.post2
  - python-igraph=0.11.9
  - leidenalg=0.10.2
  - scikit-misc=0.5.1
  - fastparquet=2024.11.0
  - pyarrow=21.0.0
  - geopandas=1.1.1